# Generated by Django 4.1.3 on 2023-01-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_cont_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='u_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='cont_tb',
        ),
        migrations.RenameField(
            model_name='mytab',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='mytab',
            name='lname',
        ),
    ]
