# Generated by Django 4.1.3 on 2023-01-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_delete_mytab'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
