# Generated by Django 4.1.3 on 2023-02-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_abc_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='num',
        ),
    ]
