# Generated by Django 4.1.3 on 2023-02-02 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_remove_abc_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
