# Generated by Django 4.1.3 on 2023-02-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_xyz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='xyz',
        ),
    ]
