# Generated by Django 4.1.3 on 2023-02-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='abc',
            new_name='ad_cart',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
