# Generated by Django 4.1.3 on 2023-02-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_rename_abc_ad_cart_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='num',
            new_name='uid',
        ),
    ]
